## Numpy Indexing & Slicing
## 20180724
## Sungjae Lee

In [27]:
import numpy as np

In [28]:
test_example = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
test_example[0][0]

1

In [30]:
test_example[0, 1]

2

In [31]:
# Matrix 0,0 에 12 할당
test_example[0,0] = 12
test_example

array([[12,  2,  3],
       [ 4,  5,  6]])

In [32]:
test_example[0, 0] = 5
test_example[0, 0]

5

#### slicing

In [36]:
test_example = np.array([
    [1, 2, 5,8], [1, 2, 5, 8],[1, 2, 5, 8],[1, 2, 5, 8]], int)
test_example

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [38]:
test_example = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
# 전체 Row의 2열 이상

test_example[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [39]:
# 1 Row의 1열 ~ 2열
test_example[1, 1:3]

array([7, 8])

In [45]:
# 1 Row ~ 2Row의 전체
test_example[1:3]

array([[ 6,  7,  8,  9, 10]])

In [48]:
a = np.arange(100).reshape(10, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
a[:,9]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [54]:
a[:,9].reshape(2, 5)

array([[ 9, 19, 29, 39, 49],
       [59, 69, 79, 89, 99]])