## Numpy Operation
## 20180724
## Sungjae Lee

In [1]:
import numpy as np

#### Arrary operations

In [3]:
test_a = np.arange(1, 7, dtype = float).reshape(2, 3)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
# Matrix + Matrix 연산
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [6]:
# Matrix - Matrix 연산
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Matrix내 element들 간 같은 위치에 있는 값들끼리 연산
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [8]:
matrix_a = np.arange(1, 13).reshape(3, 4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

#### dot product

In [9]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [11]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
test_a.dot(test_b)
# dot product 는 행렬곱을 의미한다.
# matrix * matrix 는 각각의 위치에 따라 곱하는 것이다.

array([[ 58,  64],
       [139, 154]])

In [14]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
print(test_a.T)
print(test_a.transpose())
# 모두 전치행렬을 생성하는 방법이다

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [19]:
# Matrix 간 곱셈
test_a.T.dot(test_a)
# a 의 전치행렬과 a 행렬을 행렬곱 연산 한 것이다.

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [33]:
test_b.T.dot(test_b)

array([[251, 278],
       [278, 308]])

#### broadcasting

In [34]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [35]:
# Matrix - Scalar 덧셈
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [36]:
# Matrix - Scalar 뺄셈
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [38]:
# Matrix - Scalar 곱셈
test_matrix * scalar

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [40]:
# Matrix - Scalar 나눗셈
test_matrix / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [42]:
# Matrix - Scalar 몫
test_matrix // 0.2

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [43]:
# Matrix - Scalar 제곱
test_matrix ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [45]:
test_matrix = np.arange(1, 13).reshape(4, 3)
test_vector = np.arange(10, 40, 10)
print(test_matrix, test_vector)

test_matrix + test_vector

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] [10 20 30]


array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])