## Numpy Comparison
## 20180724
## Sungjae Lee

In [1]:
import numpy as np

#### all & any

In [2]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.any(a > 5), np.any(a < 0)
# a 의 모든 원소에 대해 하나라도 만족하는 조건이 있으면 True, 모두 만족하지 않으면 False

(True, False)

In [7]:
np.all(a > 5), np.all(a < 10)

(False, True)

#### comparision operation

In [9]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b
# a 와 b의 모든 요소에 대해 각각 비교하여 True / False 를 어레이로 반환

array([False,  True, False])

In [21]:
test_a == test_b

array([False, False, False])

In [24]:
(test_a > test_b).any()

True

In [25]:
a = np.array([1, 3, 0], float)
# and 조건의 condition
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [26]:
b = np.array([True, False, True], bool)
# NOT 조건의 condition
np.logical_not(b)

array([False,  True, False])

In [28]:
c = np.array([False, True, False], bool)
# OR 조건의 condition
np.logical_or(b, c)

array([ True,  True,  True])

In [30]:
a = np.array([1, 3, 0], dtype = np.float)
a

array([1., 3., 0.])

In [31]:
# where(condition, TRUE, FALSE)
np.where(a > 0, 3, 2)

array([3, 3, 2])

In [38]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
np.where(a > 5)
# 조건식이 True 인 index 값이 반환된다.

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),)

In [43]:
a = np.array([1, np.NaN, np.Inf], float)
print(a)
print(np.isnan(a))

[ 1. nan inf]
[False  True False]


In [44]:
np.isfinite(a)

array([ True, False, False])

#### argmax & argmin

In [50]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)
print(a[np.argmax(a)], a[np.argmin(a)])

78 1


In [51]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis = 1), np.argmin(a, axis = 0)

(array([3, 1, 1]), array([0, 0, 2, 2]))